# Generated by Django 3.2.25 on 2025-02-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('client', 'Client')], default='client', max_length=10),
        ),
    ]
